### ISSUE TITLE
Switching layouts fails to load the window

### ISSUE THREAD

**Issue by ScottBeck89** [marijnz/unity-toolbar-extender#1]
When switching to a different layout the button disappears, this is related to a known issue that Unity isn't worried about fixing.

https://issuetracker.unity3d.com/issues/unity-doesnt-open-a-custom-editor-window-that-is-a-part-of-a-custom-layout

**Comment by marijnz** [comment]
Hey. I didn't reply but definitely saw it :). As it's a known issue for Unity, it can be considered out of scope for this project and I'm therefore inclined to close this issue as it's not actionable. Do you think otherwise?

**Comment by ScottBeck89** [comment]
Yea that's what I found as well. Close it up!
