### ISSUE TITLE
Unity 2020.1 compatability

### ISSUE THREAD

**Issue by MaxStriebel** [marijnz/unity-toolbar-extender#15]
In Unity 2020.1 UnityEditor.GUIView doesn't have a "visualTree" property animore. This results in a Null reference exception on line 46 in ToolbarCallback

**Comment by marijnz** [comment]
Good to know, if anyone wants to look into this.. :)

**Comment by garrafote** [comment]
I fixed the problem on Unity 2020.1.0b13.

Also, it seems that there is now a new internal API that allows hooking custom ui to the toolbar. It looks to me that unity is already using this new method with the "Preview Packages in Use" warning message and from what I've seen in the code all hooked UI will be placed next to the cloud button.
![image](https://user-images.githubusercontent.com/860128/86265898-cc969600-bb9a-11ea-8803-41500cd1cc39.png)

I might take a look at this later and see if I can hook something using this new method as it looks cleaner and possibly lighter than the one currently used by this package. If I manage to come up with a nice solution I'll add it as an extra callback.

**Comment by MaxStriebel** [comment]
Uh nice. Thank you very much.
