### ISSUE TITLE
Support Unity Package Manager

### ISSUE THREAD

**Issue by brogan89** [marijnz/unity-toolbar-extender#16]
It would be cool if the project would support the Unity Package Manager.
I have made a start to this in [my fork](https://github.com/brogan89/unity-toolbar-extender)  if you wanted to check it out. 

The only major thing is I removed the examples as the developer can't remove them if they want because packages are immutable. I'm not really sure how to handle that. 

If you want to go down this route I can make a way to turn off examples so developer doesn't need to see them. 

Thanks for this code, it is very handy :)

**Comment by bgr** [comment]
There is a way to include examples, I've already reorganized the files on [my fork](https://github.com/bgr/unity-toolbar-extender). I'd say it's good to merge, the only thing that might need changing are the URLs in package manifest, to be to @marijnz's liking.

**Comment by brogan89** [comment]
Nice I didn't know you could do that with the folder names. I need to look into how UPM works. It was a better idea to make it a new branch too. I knew someone would've done this already but I couldn't be bothered going through each fork to see if someone had. I think I will delete my fork and use yours now 😄 

One thing I'm confused by though is Unity ignores the `Example~` folder so would a developer be able to see the examples in use without manipulating the directory name or path? 

Also, your fork doesn't have the new editor skin fixes, but I wouldn't pull from upstream just yet, there is a compiler error caused by #14 but I've made a fix in #17 waiting to be merged. Its a simple fix though, so you could pull it and then create a PR with your fork? That's to say Marijnz even wants to go this way.

**Comment by brogan89** [comment]
I just discovered [OpenUPM ](https://github.com/openupm/openupm) would be even cooler to add it to this

**Comment by bgr** [comment]
> One thing I'm confused by though is Unity ignores the `Example~` folder so would a developer be able to see the examples in use without manipulating the directory name or path?

Yes, it's a feature of the package manager. It looks like this:
![image](https://user-images.githubusercontent.com/425768/81058845-935de480-8ecf-11ea-907a-31459c24782d.png)

> Also, your fork doesn't have the new editor skin fixes, but I wouldn't pull from upstream just yet, there is a compiler error caused by #14 but I've made a fix in #17 waiting to be merged. Its a simple fix though, so you could pull it and then create a PR with your fork? That's to say Marijnz even wants to go this way.

That'd be an unrelated change in my PR so I'll wait for that to get sorted out in this repo and then I'll update mine and make a PR.

**Comment by marijnz** [comment]
Didn't see the examples feature before. Looks interesting! I'd merge a PR for packages support if there is one :)

**Comment by bgr** [comment]
Made the PR #18

**Comment by MileyHollenberg** [comment]
Hi, when I go to https://openupm.com/packages/com.marijnzwemmer.unity-toolbar-extender/ I don't yet see a install version available. I'm using this package in my own package and the creator of OpenUPM asked me if I was interested in publishing it there as well, which I am, but I rely on your package being available there first. When could I expect the install on OpenUPM to work as expected for your package?

**Comment by favoyang** [comment]
Hi @marijnz,

I'm the creator of OpenUPM. All you need to do is creating a new GitHub release `v1.2.0` from your master branch. Our build pipelines will catch up in 5~10 minutes to release a package.

Further reading
- Managing release with CLI: https://medium.com/openupm/how-to-maintain-upm-package-part-4-managing-package-release-with-cli-972ff5311163
- Or managing release with CI: https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c

**Comment by marijnz** [comment]
Hi @favoyang. Nice to meet you. I just did that, let's see :)

**Comment by favoyang** [comment]
https://openupm.com/packages/com.marijnzwemmer.unity-toolbar-extender/

Thanks. It looks good.

**Comment by MileyHollenberg** [comment]
Thanks! Now I can update my package to use this one as well :D
