### ISSUE TITLE
Issues on OpenUPM site

### ISSUE THREAD

**Issue by bgr** [marijnz/unity-toolbar-extender#21]
I've noticed the following on https://openupm.com/packages/com.marijnzwemmer.unity-toolbar-extender/
#20 might fix it, or maybe a new release (possibly with bump to 1.3.1) might be required, I'm not familiar with how it works.

Screenshot:
![image](https://user-images.githubusercontent.com/425768/94269282-bea8a500-ff3e-11ea-8401-87c76a1b5f67.png)

**Comment by marijnz** [comment]
Heya. I created another new version and it's no longer conflicted.
