### ISSUE TITLE
broken in 2020.2.0f1

### ISSUE THREAD

**Issue by cosmogonies** [marijnz/unity-toolbar-extender#22]
Hi, Unity just releases 2020.2.0f1,
and unfortunately your hack fails now, it seems that some modifications have changed in that UI.
(m_viewVisualTree is null now)

Do you think you can find a way to still find the toolbar ?
Your plugin is sooo helpful !

The UI debugger works with the toolbar, if that can help you:
![image](https://user-images.githubusercontent.com/3942295/102709224-9f54b600-42a8-11eb-97ce-e47932504fb6.png)

Thank you^^

**Comment by Team-on** [comment]
Well, this package use same code and works well. 
https://github.com/smkplus/CustomToolbar
So I think you can look into that

**Comment by cosmogonies** [comment]
Oh thank you.
I see the error since my update, but I did not find that the package changes since I integrated it^^
Silly me, works great now ! (I close the ticket)
