### ISSUE TITLE
Doesnt work in 2021.

### ISSUE THREAD

**Issue by MartinCapousek** [marijnz/unity-toolbar-extender#23]
It properly draw GUI but it doesn't handle mouse events properly... drop-down doesn't open, etc.

**Comment by BennyKok** [comment]
I face the same problem and went up did my own solution with VisualElement https://github.com/BennyKok/unity-toolbar-buttons/blob/899476263c94d392d869ca22f49b58c3f8fca4c3/Editor/ToolbarButtons.cs#L91
If you want to get with some toolbar buttons working out of the box you can take a reference from here, similar reflection approach, but much simpler with VisualElement injection in 2021.

**Comment by marijnz** [comment]
Probably makes sense to update this repo with that approach. Is somebody feels like doing so! :) I'd gladly accept any PR.

**Comment by oleghcp** [comment]
So, any news?

**Comment by marijnz** [comment]
Someone wants to implement this? :)

**Comment by marijnz** [comment]
Added support - https://github.com/marijnz/unity-toolbar-extender/releases/tag/v1.4.1

Let me know if it works well for you.

**Comment by marijnz** [comment]
I'm closing this as it hsould be solved.
