### ISSUE TITLE
Unity 2023.1.0 a25 icon alignment issue

### ISSUE THREAD

**Issue by larssteenhoff** [marijnz/unity-toolbar-extender#33]
![Screenshot 2023-01-13 at 19 56 10](https://user-images.githubusercontent.com/9589240/212397508-d8c8233f-80e3-4525-8030-3e60554693e0.png)

In Unity 2023.1.0 a25

The icons ar not aligned in the center of the button but on the left as can be seen in the screenshot.
Perhaps its a unity beta bug, or unity has changed something.

**Comment by marijnz** [comment]
Hey, I'm personally not on that version yet. Anyone can feel free to submit a fix for this, but given that it's alpha it might indeed be just a bug that's fixed in a next version. Let's keep updates tracked here.

**Comment by larssteenhoff** [comment]
Seems to be fixed in the latest 2023 version
