### ISSUE TITLE
Alternative approach

### ISSUE THREAD

**Issue by OndrejPetrzilka** [marijnz/unity-toolbar-extender#4]
Hey, I was thinking about different approach:

1. Create wrapper class deriving from Toolbar
2. Override OldOnGUI(), provide callback
3. Replace instance of the Toolbar in Editor

Sounds impossible, but it actually isn't.

1. To derive from Toolbar, you'll have to do it in IL, because it's internal. See attached IL file. You can ignore GameObjectEditor that's something else :)
I've also attached mockup of classes, which I compile and then disassemble into IL
[UnityIL.Editor.il.txt](https://github.com/marijnz/unity-toolbar-extender/files/2563415/UnityIL.Editor.il.txt)
[Mockup.cs.txt](https://github.com/marijnz/unity-toolbar-extender/files/2563427/Mockup.cs.txt)

2. There's internal `ToolbarWrapper` and static class `ToolbarExtension` which exposes callbacks and other useful methods (see mockups)

3. Create wrapper, copy all serialized properties, replace it
`MainView.children[0]` is always Toolbar, just replace it
There's also `Toolbar.get` (field surprisingly), which is probably a good idea to replace
[ToolbarExtension.cs.txt](https://github.com/marijnz/unity-toolbar-extender/files/2563439/ToolbarExtension.cs.txt)

IL compilation command:
`c:\Windows\Microsoft.NET\Framework\v2.0.50727\ilasm UnityIL.Editor.il /dll /OUTPUT=%~dp0UnityIL.Editor.dll`

Simple case works, see screenshot below.
I've encountered some issues when switching layout (not sure why).
Done on Unity 2018.2.10f1

![toolbarext](https://user-images.githubusercontent.com/3371096/48225369-e0c1ca00-e39c-11e8-893e-cc9d8ad54c43.png)

**Comment by OndrejPetrzilka** [comment]
This approach is complicated and has issues, there's better approach #5

**Comment by marijnz** [comment]
Plus points for creativity :)
